### PR TITLE
explicit format fields for compatibility with python2.6 / added min/maxProperties

### PR DESCRIPTION
**Pull request by Heiko-san**
Since this is kind of a "low hanging fruit" I decided to fix this, maybe you want to merge it :)

I successfully testet the named format strings and some occurrences of {0!r} for compatibility with python2.6

### CODE REVIEW

**Comment by Heiko-san** [comment]
Hmm, I don't get coveralls :/
What tests does it think are still missing?
I had a look at your tests for min/maxLength and build the same, but still it complains 
Coverage decreased (-0.5%) to 95.957% when pulling e6e128b

**Comment by jamesturk** [comment]
I wouldn't worry about the 0.5% decrease, I'll find some time fairly soon to look over these PRs, thanks!

**Comment by Heiko-san** [comment]
No problem , these were actually easy and not too time consuming.
Maybe I'll analyse my bug issue at weekend ^^
Btw: this module is really great work!

**Comment by jamesturk** [comment]
with this change do all the tests pass on 2.6?  I'm torn about supporting it at all, but if it is such a simple change and that's all I'm open to it

**Comment by Heiko-san** [comment]
Well ... actually I had a lot of trouble getting the unittests itself to run, but they succeed:
```
[root@653cf5249e9e tests]# pwd
/opt/monitoring/pythonlibs/validictory/tests
[root@653cf5249e9e tests]# python --version
Python 2.6.6
[root@653cf5249e9e tests]# for i in $(ls | grep test_ | grep -v '.pyc$'); do echo $i ; PYTHONPATH=../../ python ./$i ; done
test_apply_default.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
test_disallow_unknown_properties.py
....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
test_fail_fast.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
test_items.py
............
----------------------------------------------------------------------
Ran 12 tests in 0.004s

OK
test_other.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
test_properties.py
...................
----------------------------------------------------------------------
Ran 19 tests in 0.006s

OK
test_remove_unknown_properties.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
test_schema_schema.py
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
test_type.py
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.012s

OK
test_values.py
............................................................
----------------------------------------------------------------------
Ran 60 tests in 0.016s

OK
[root@653cf5249e9e tests]# 
```
But actually I think there is no need to officially support python2.6, but would be a nice to have to provide the explicit format fields so it will actually run on python2.6 (if officially supported or not).

**Comment by Heiko-san** [comment]
Hi,

any new status here?

**Comment by jamesturk** [comment]
sorry, didn't realize this had the min/max properties stuff on the same branch, thanks!

**Pull request merged**
